- name: installing catalogue microservice
  hosts: catalogue
  tasks:
  - name: setting up nodejs-repos with vendor provided script
    ansible.builtin.script: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  - name: installing the nodejs
    ansible.builtin.yum:
      name: nodejs
      state: started
  - name: checking if user roboshop exits or not
    ansible.builtin.command: id roboshop
    register: output
    
  