- name: creation of user with shankar name
  hosts: localhost
  tasks:
  - name: checking user exits or not
    ansible.builtin.command: id shankar
    register: output
    ignore_errors: true
  - name: printing the output of user exits or not
    ansible.builtin.debug:
      msg: "{{output}}"
  - name: checking existing status
    ansible.builtin.debug:
      msg: "{{output.rc}}"
  - name: creation od user if not exits
    become: yes
    ansible.builtin.user:
      name: shankar
    when: output.rc != 0