- name: printing simple condition
  hosts: localhost
vars:
  name: Devops
  tasks:
  - name: printing the course name
    ansible.builtin.debug:
      msg: "course name is:{{name}}"
      when: name == "Devops"